### ISSUE TITLE
Reimplement Hakyll's metadata `listField`

### ISSUE THREAD

**Issue by L-TChen** [flolac-tw/main_site#7]
A page may consist of events specified by time, subject, and its content in the yaml front matter as 
```
  - events:
    - time: ...
      subject: ...
      content: ...
    - time: ...
      subject: ...
      content: ...
```
Ideally, the metadata includes a key called `events` which is a list of tuples. Then, I'd like to access it as `$i.time$` via an iterator `i`. The template syntax might need an additional `for-each` macro.
